
---
title: Communication
bibliography: Resources/biblio_web.bib
format:
  html:
    page-layout: full
---

## {{< iconify fa-solid:pen-nib >}} &nbsp; Scientific writing 

::: {.talk-card}


### General tips and tools

* The package [microtype](https://ctan.org/pkg/microtype) helps improving the rendering of long text easily

* [Quarto](https://quarto.org) is an open-source library that enables to create dynamic scientific documents, presentations, and websites using Markdown, LaTeX, and a variety of programming languages (including python, R, etc.).
* Good practices regarding figure formating
  * Colour science [@crameriMisuseColourScience2020a] and colour map choices
  * 10 rules for better figures in scientific writting [@rougierTenSimpleRules2014a]
  * Nice tool for plotting data in latex: [PGFplot](https://pgfplots.net)

:::

:::{.talk-card}

### Templates

* This [PhD template](https://github.com/floiseau/PhD_Thesis_Template) is for writting a PhD thesis with a separate title page.
It aims at setting up all the necessary packages and create the base outline of a thesis.

* This [quarto template](https://github.com/AlexandreDabySeesaram/Slideshow_Template) is for presentations with an ENSTA style.


:::



## {{< iconify fa6-solid:compass-drafting >}} &nbsp; Figures editing

::: {.talk-card}

### Miscellaneous

* Scientific drawing with inkscape monthly letter [here](https://dsinkscape.substack.com/about).
* Good practices regarding figure formating
  * Colour science [@crameriMisuseColourScience2020a] and colour map choices
  * 10 rules for better figures in scientific writting [@rougierTenSimpleRules2014a]
  * Nice tool for plotting data in latex: [PGFplot](https://pgfplots.net/)

:::
